project:
  type: website
  output-dir: docs

lang: en

website:
  title: "Reproducibility Guide"
  
metadata:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "FAIR Principles"
        href: source/fair.qmd
      - text: "Version control"
        href: source/version_control.qmd
      - text: "Workflow"
        href: source/workflow.qmd
      - text: "Codestyle"
        href: source/codestyle.qmd

  page-footer:
    left: "© 2026 Department Psychology of Digitalisation"
    center:
      - text: "<i class='bi bi-github'></i> GitHub"
        href: https://github.com/schillinglars/reproducibility_guide
      - text: "<i class='bi bi-globe'></i> Department website"
        href: https://www.dig.psy.unibe.ch/index_eng.html
    right: "Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"

format:
  html:
    theme: flatly
    primary: "#7a1f1f" #ToDo: Adjust to departments official color scheme
    email-obfuscation: javascript # Hide clear mail addresses from bots
    toc: true
    code-copy: true
    code-fold: show
    css: styles.css