project:
  type: website
  output-dir: docs

lang: en

website:
  title: "Reproducibility Guide"
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "Getting Started"
        contents:
          - text: "Reproducibility"
            href: content/reproducibility.qmd
          - text: "Workflow"
            href: content/workflow.qmd
      - section: "The Toolbox"
        contents:
          - text: "Version Control"
            href: content/version_control.qmd
      - section: "Data & Ethics"
        contents:
          - text: "FAIR Principles"
            href: content/fair.qmd

  page-footer:
    left: "© 2026 Department Psychology of Digitalisation"
    right: "Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"

format:
  html:
    toc: true
    code-copy: true
    code-fold: show
    css: styles.css