project:
  type: website
  render:
    - "*.qmd"
    - "!scripts/data_simulation.qmd"
  output-dir: docs

lang: en

website:
  title: "Reproducibility Guide"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "0. Welcome"
        href: index.qmd
      - text: "1. FAIR Principles"
        href: source/fair.qmd
      - text: "2. Version control"
        href: source/version_control.qmd
      - text: "3. Workflow"
        href: source/workflow.qmd
      - text: "4. Codestyle"
        href: source/codestyle.qmd
      - text: "5. Template"
        href: source/template.qmd

  page-footer:
    left: "© 2026 Department Psychology of Digitalisation"
    center:
      - text: "<i class='bi bi-github'></i> GitHub"
        href: https://github.com/schillinglars/reproducibility_guide
      - text: "<i class='bi bi-globe'></i> Department website"
        href: https://www.dig.psy.unibe.ch/index_eng.html
    right: "Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"

format:
  html:
    theme: flatly
    primary: "#7a1f1f" #ToDo: Adjust to departments official color scheme
    email-obfuscation: javascript # Hide clear mail addresses from bots
    toc: true
    css: styles.css # Custom CSS for styling
    code-fold: true # Hide code by default
    code-tools: true # Add the "Code" menu at the top right
    code-copy: true # Allow easy copying of snippets
    code-link: true # Hyperlinks to functions documentations