---
title: "Reproducibility Guide"
subtitle: "General information"
date: last-modified
bibliography: source/references.bib
csl: source/apa.csl
---

{{< include _hardcoded_values.qmd >}}

This is the landing page of the reproducibility guide of the Department *Psychology of Digitalisation* at the University of Bern. This guide aims to give students an introduction to reproducible and clean code for their thesis projects.

::: {.callout-important}
Whatever the content of this guide, please note that any guidelines from your supervisor are always superior to the guidelines provided here. This guide is intended to be a helpful resource, but it cannot replace the specific requirements and expectations of your supervisor. Always prioritize the instructions and feedback from your supervisor when working on your thesis.
:::

For your orientation: The content of this guide is mostly written such that the guidelines can be followed independently for any programming language but for Quarto used within the IDE of RStudio. The examples provided focus on the programming language of R as this is the most commonly used one for data analysis in psychology. If a particular guideline applies differently to the programming language of Python, this will be marked explicitly in the text via the following information box:

::: box-python
Content related in particular to Python will be placed in these information boxes.
:::

This guide is hosted on GitHub and is open for contributions. If you have suggestions for improvement, please let us know by creating an issue on the [GitHub repository][repo-url] or by [contacting us directly][contact].

The guide is inspired by the [Guide to Reproducible Code](https://bes-guide.github.io/reproducible-code/) from the British Ecological Society (BES).

## References

::: {#refs}
:::