---
title: "Reproduzierbarkeit"
date: today
---

# FAIR

Um Forschungsergebnisse transparenter und nachvollziehbarer zu machen, gibt es die sogenannten FAIR-Prinzipien (Findable, Accessible, Interoperable, Reusable). Hier ist erklärt, was diese bedeuten und wie wir sie durch RStudio besser umsetzen können:

1.  **Findable**: Software sollte für Mensch und Maschiene leicht auffindbar sein. Ausserdem sollte Software einen klar zuordbaren Identifer besitzen

    Die verwendete Version von R und RStudio kann über die Funktion `sessionInfo()` abgefragt werden. So können dritte genau nachvollziehen, welche Versionen der Software verwendet wurden. Über die offiziellen Stellen von CRAN (für R) und Posit (für RStudio) können diese dann recherchiert werden.

```{r, eval = FALSE}
sessionInfo()
```

2.  **Accessible**: Software sollte für Menschen und Maschinen zugänglich sein, idealerweise über eine öffentliche Lizenz.

    R und RStudion sind beide *Open source* Software. Der Quellcode hinter der Programmiersprache R und hinter der Enwicklungsumbegung von RStudio ist einsehbar, darf verändert und weiter verbreitet werden.

3.  **Interoperable**: Software sollte mit anderen Softwareprodukten und Daten kompatibel sein, um die Zusammenarbeit und den Austausch von Informationen zu erleichtern. Dies kann durch die Verwendung von offenen Standards und Schnittstellen erreicht werden.

    R und RStudio unterstützen eine Vielzahl von Paketen, die von der Community entwickelt wurden. Diese Pakete ermöglichen es beispielsweise Daten aus verschiedenen Quellen zu importieren (Excel-Dateien, JSON-Dateien, Dateien direkt von Websiten etc.) und diese auch wieder in unterschiedliche Formate zu exportieren.

4.  **Reusable**: Software sollte so gestaltet sein, dass sie von anderen Forschern leicht wiederverwendet werden kann. Hierzu gehört, dass sie verständlich dokumentiert ist, auf ihr aufbauend Modifizierungen vorgenommen werden können oder sie in eine andere Software integrierbar ist.

    In Quarto geschriebene Dateien enden auf .qmd und sind somit auch von anderen Programmen lessbar. Packages in R haben, sofern sie auf der offiziellen Website von [CRAN](https://cran.rstudio.com/) gelistet sind, immer auch eine ausführliche Dokumentation.

Achte unabhängig von der Software, die du verwendest, darauf, dass du die FAIR-Prinzipien so gut wie möglich umsetzt. So kannst du sicherstellen, dass deine Forschungsergebnisse transparent und nachvollziehbar sind und von dritten leicht wiederverwendet werden können.
