---
title: "FAIR principles"
---

{{< include ../_hardcoded_values.qmd >}}

To make research results more reproducible, there are the so-called **FAIR principles (Findable, Accessible, Interoperable, Reusable)**. Research projects, including your thesis, should follow these principles wherever possible. In particular for code and software, these principles can be applied as follows:

1.  **Findable**: The whole content should be easily locateable. This can be achieved through the use of unique identifiers, metadata, naming conventions, and folder structures which follow guidelines and contain descriptive information about the content.

    *One example: You set up the folder system in your project to match the [psychDS-structure](https://psych-ds.github.io/) and place your data in the respective subfolder `/data/` with meaningful and machine readable names like `data_merged`.*

2.  **Accessible**: All the material should be accessible to everyone. This can be achieved by using open access repositories, providing clear instructions for accessing the material, and ensuring that the material is available in a format that can be easily used by others. Further, all applied software should be open source and freely available to everyone.

    *One example: Instead of a proprietary software you use tools like Python or R which are open-source and you place all your material on openly available plattforms like your public GitHub repository.*

3.  **Interoperable**: Software and code should be compatible with other software products and data to facilitate collaboration and the exchange of information. This can be achieved through the use of open standards and interfaces.

    *One example: You save your data in open formats like `.csv`, `.parquet` or `.json` to ensure compatibility across different programming languages and operating systems.*

4.  **Reusable**: Software should be designed so that it can be easily reused by other researchers. This includes ensuring that it is clearly documented, allowing for modifications to be built upon it, or making it integratable into other software.

    *One example: You include a LICENSE file to legally permit others to use your work and a README to explain the content of your project.*

The following pages provide practical guidance on implementing the FAIR principles more comprehensively in your work. While this is not an exhaustive list, it serves as a robust starting point for making your research more transparent and reproducible. As you write your thesis, keep the FAIR principles in mind and look for opportunities to align your workflow even more closely to them.

::: callout-note
If you are interested in a more comprehensive overview of the FAIR-Principles and their application in research, check out the [FAIR Principles website](https://www.go-fair.org/fair-principles/).
:::
