---
title: "Project setup"
bibliography: references.bib
csl: apa.csl
---

{{< include ../_hardcoded_values.qmd >}}

## Fundamentals

At the core of a robust, reproducible analysis is a project setup which is based on a **script-based** workflow. This ensures that every step of your data processing pipeline is documented and can be re-executed with a single command. A well-organized project structure is the prerequisite for this automation, making your research transparent, traceable, and easy to share. Here you can see an exemplary folder structure for a script-based workflow:

``` text
Parent_Folder/
├── project.Rproj         # Project  information
├── code/                 # All code
│   ├── analyses.qmd      # Analysis script
│   └── analyses.html     #
├── data/                 # All inputs
│   ├── raw/              # Raw data
│   └── processed/        # Processed data
├── outputs/              # All non-data outputs
│   ├── figs/             # Generated plots and graphs
│   └── tables/           # Generated tables
├── README.md             # Brief project explanation
├── licence.txt           # License information
└── references.bib        # Citation information
```

### Project file

An RStudio Project file (file extension *.Rproj*), which we had created on the previous page, serves as the "anchor" for your work. It defines the root directory of your project. With a project file opened in the IDE of **RStudio** it is possible and **highly recommended** to seamlessly integrate version control via Git and GitHub, and to set relative paths. These two topics will be covered later on in this guide.

### Code

The folder for `code` contains all **scripts**, like the one we created on the previous page, which are at the heart of reproducibility. These connect your raw data to your processed data and other output. By coding every single step, you eliminate the risk of "forgotten" manual edits and ensure that anyone, including your future self, can reproduce the results. The basic script is always the Quarto file and the output of a rendered Quarto file is typically the final report (e.g., in HTML).

::: callout-note
If you are not familiar with Quarto or the IDE of RStudio in general yet, on the following page you can find a brief introduction on how to use it within the scope of this guide.
:::

::: box-python
If you have installed python on your device, it is generally possible to run both Python and R code within the same script. For the IDE of RStudio, this can be achieved by using Quarto documents (file extension *.qmd*). Check out the official [Quarto documentation](https://quarto.org/docs/computations/python.html) for more information on how to set up and use Python within Quarto.
:::

### Data

Raw data is the "source of truth" and must remain **immutable** (taking into account privacy concerns and anonymisation). Once stored in `data/raw/`, these files should never be edited manually. This ensures the raw data as basement for all other parts so that these can potentially always be recovered.

Processed data is technically 'disposable' because it can always be re-generated by running your scripts again on the raw data as input. The resulting data files are stored in `data/processed/`. This strict separation ensures that your analysis always builds upon a clean foundation without ever risking accidental overwrites of your original observations.

### Outputs

All figures and tables generated by the scripts belong in the `outputs/` folder. Like with the processed data files, they are created completely automatically and hence they are technically "disposable". You can delete them at any time and recreate them perfectly by re-running your scripts on the raw data as input via a single command.

### README

The README (file extension *.md*) is the manual for your project. It is the first file a collaborator or supervisor will read to understand and potentially contribute to the project. A good README should include:

-   *Brief Description*: What is the study about?

-   *Project Structure*: Where is the data and what is the order in which the scripts should be executed?

-   *Instructions for Reproduction*: Which software is required and how can the scripts be executed to reproduce the results?

-   *Licensing*: Should others cite your work, and is it allowed to reuse the code?

Note that the licensing can be stated elsewhere and is not obligatory in a README.

### License

Make sure your work is credited accordingly so that third parties know what they are allowed to do with and what not. As stated earlier, the license can be stated within the README or in a separate file (e.g., *license.txt*). You can find typical licenses for research projects with assicated information [here](https://help.osf.io/article/148-licensing). If you are unsure what license to use, consult your supervisor.

### Citation

Quarto makes it possible to include citations automatically by using a BibTeX (file extension *.bib*) file.

A standard entry within a BibTex-file looks like this:

``` text
@book{wickham2023,
  author = {Wickham, Hadley and Mineault, Patrick},
  title = {R for Data Science},
  year = {2023},
  publisher = {O'Reilly Media},
  edition = {2nd edition}
}
```

The YAML header of the Quarto document should include the following lines to link the BibTeX file and the citation style file (e.g. APA 7 Style; can be found and downloaded from [Zotero Style Repository](https://www.zotero.org/styles)):

`bibliography: references.bib`

`csl: apa.csl`

You can cite the work by using the key defined in your `.bib` file, which is usually the surname of the first author followed by the year of publication. For example, if you want to cite the above book, you would use `@wickham2023` in your text. But you can also cite the work parathetically by using `[@wickham2023]` in your text. The citation will then be automatically formatted according to the specified style (e.g., APA, MLA, Chicago) and included in the bibliography section of your document.

To include a bibliography section in your document, simply add the citation as described above and the Reference section will be automatically generated at the end of your document:

@wickham2023

### References

::: {#refs}
:::

::: callout-note
To see a real-life example of a script based workflow check out the repository of this website \[here\]\[repo-url\] and additionally the code of each page via the `</>Code`-button in the top right corner.
:::

::: callout-note
The project setup described here is a simplified version of the [psych-DS](https://psych-ds.github.io/) standard. For more detailed information, feel free to explore their official documentation. Ian Hussey from our lab has developed the R package [`psychdsish`](https://github.com/ianhussey/psychdsish), which can be used to generate a structure that adheres to the full psych-DS specifications or to validate an existing project.
:::
