---
title: "Workflow"
bibliography: references.bib
csl: apa.csl
---

{{< include ../_hardcoded_values.qmd >}}

# Fundamentals

The core of a robust, reproducible analysis is a **script-based** workflow. This ensures that every step of your data processing is documented and can be re-executed with a single command. A well-organized project structure is the prerequisite for this automation, making your research transparent, traceable, and easy to share. Here you can see an exemplary folder structure for a script-based workflow:

``` text
Parent_Folder/
├── project.Rproj         # Project file
├── data/                 # All analysis inputs
│   └── raw/              # Raw data
├── scripts/              # All analysis scripts
│   └── analyses.qmd      # Main script
├── outputs/              # All analysis outputs
│   ├── figs/             # Graphics and plots
│   └── tables/           # Tables
├── README.md             # Brief project explanation
├── licence.txt           # License information
└── references.bib        # BibTex file
```

## Project

An RStudio Project file (file extension *.Rproj*) serves as the "anchor" for your work. It defines the root directory of your project. Such files are **highly recommended** to seamlessly integrate version control via Git and GitHub directly in the IDE of **RStudio**.

## Raw data

Raw data is the "source of truth" and must remain **immutable**. Once stored in `data/raw/`, these files should never be edited manually. This ensures the raw data as basement for all other parts so that these can potentially always be recovered.

## Scripts

As the name of the **script-based** workflow suggests, the script is the heart of it. It connects your raw data to your final results. Every step from data cleaning to visualization must be coded. This eliminates the risk of "forgotten" manual steps in e.g. Excel and ensures that anyone (including your future self) can reproduce your exact results.

::: box-python
If you have installed python on your device, it is generally possible to run both Python and R code within the same script. For the IDE of RStudio, this can be achieved by using Quarto documents (file extension *.qmd*). Check out the official [Quarto documentation](https://quarto.org/docs/computations/python.html) for more information on how to set up and use Python within Quarto.
:::

## Outputs

All figures and tables generated by the scripts belong in the `outputs/` folder. Since they are created completely automatically, they are technically "disposable". You can delete them at any time and recreate them perfectly by re-running your scripts via a single command.

## README

The README (file extension *.md*) is the manual for your project. It is the first file a collaborator or supervisor will read to understand and potentially contribute to the project. A good README should include:

-   *Brief Description*: What is the study about?

-   *Project Structure*: Where is the data and what is the order in which the scripts should be executed?

-   *Instructions for Reproduction*: Which software is required and how can the scripts be executed to reproduce the results?

-   *Licensing*: Should others cite your work, and is it allowed to reuse the code?

Note that the licensing can be stated elsewhere and is not obligatory in a README.

## License

Make sure your work is credited accordingly so that third parties know what they are allowed to do with and what not. As stated earlier, the license can be stated within the README or in a separate file (e.g., *license.txt*). If you are unsure what license to use, consult your supervisor.

## Citation

Quarto makes it possible to include citations automatically by using a BibTeX (file extension *.bib*) file.

A standard entry within a BibTex-file looks like this:

atbook{wickham2023,
  author = {Wickham, Hadley and Mineault, Patrick},
  title = {R for Data Science},
  year = {2023},
  publisher = {O'Reilly Media},
  edition = {2nd edition}
}

The YAML header of the Quarto document should include the following lines to link the BibTeX file and the citation style file (e.g. APA 7 Style; can be found and downloaded from [Zotero Style Repository](https://www.zotero.org/styles)):

`bibliography: references.bib`

`csl: apa.csl`

You can cite the work by using the key defined in your `.bib` file, which is usually the surname of the first author followed by the year of publication. For example, if you want to cite the above book, you would use `@wickham2023` in your text. But you can also cite the work parathetically by using `[@wickham2023]` in your text. The citation will then be automatically formatted according to the specified style (e.g., APA, MLA, Chicago) and included in the bibliography section of your document.

To include a bibliography section in your document, you can add the following line at the end of your Quarto document:

@wickham2023

# References

::: {#refs}
:::

::: callout-note
To see a real-life example of a script based workflow check out the repository of this website [here]({{< repo-url >}}) and additionally the code of each page via the `</>Code`-button in the top right corner.
:::
